final Map<String, dynamic> beginnerItalianCourse = {
  'language': 'italian',
  'proficiency': 'beginner',
  'lessons': [
    // ========== GREETINGS (10 lessons) ==========
    {
      'lessonId': 'greeting_1',
      'order': 1,
      'category': 'greetings',
      'content': 'Ciao',
      'translation': 'Hello/Goodbye',
      'pronunciation': 'chow',
      'notes': 'Informal, used with friends'
    },
    {
      'lessonId': 'greeting_2',
      'order': 2,
      'category': 'greetings',
      'content': 'Buongiorno',
      'translation': 'Good morning',
      'pronunciation': 'bwon-jor-no',
      'notes': 'Use until about 1 PM'
    },
    {
      'lessonId': 'greeting_3',
      'order': 3,
      'category': 'greetings',
      'content': 'Buon pomeriggio',
      'translation': 'Good afternoon',
      'pronunciation': 'bwon po-meh-ree-joh',
      'notes': 'Used from 1 PM until evening'
    },
    {
      'lessonId': 'greeting_4',
      'order': 4,
      'category': 'greetings',
      'content': 'Buonasera',
      'translation': 'Good evening',
      'pronunciation': 'bwon-ah-seh-rah',
      'notes': 'Used from late afternoon'
    },
    {
      'lessonId': 'greeting_5',
      'order': 5,
      'category': 'greetings',
      'content': 'Buonanotte',
      'translation': 'Good night',
      'pronunciation': 'bwon-ah-not-teh',
      'notes': 'When going to bed'
    },
    {
      'lessonId': 'greeting_6',
      'order': 6,
      'category': 'greetings',
      'content': 'Arrivederci',
      'translation': 'Goodbye',
      'pronunciation': 'ah-ree-veh-der-chee',
      'notes': 'Formal farewell'
    },
    {
      'lessonId': 'greeting_7',
      'order': 7,
      'category': 'greetings',
      'content': 'Come stai?',
      'translation': 'How are you? (informal)',
      'pronunciation': 'koh-meh stai',
      'notes': 'Use with friends'
    },
    {
      'lessonId': 'greeting_8',
      'order': 8,
      'category': 'greetings',
      'content': 'Come sta?',
      'translation': 'How are you? (formal)',
      'pronunciation': 'koh-meh stah',
      'notes': 'Use with strangers/elders'
    },
    {
      'lessonId': 'greeting_9',
      'order': 9,
      'category': 'greetings',
      'content': 'Sto bene',
      'translation': 'I am well',
      'pronunciation': 'stoh beh-neh'
    },
    {
      'lessonId': 'greeting_10',
      'order': 10,
      'category': 'greetings',
      'content': 'E tu? / E Lei?',
      'translation': 'And you? (informal/formal)',
      'pronunciation': 'eh too / eh lay'
    },

    // ========== BASICS (10 lessons) ==========
    {
      'lessonId': 'basic_1',
      'order': 11,
      'category': 'basics',
      'content': 'Sì',
      'translation': 'Yes',
      'pronunciation': 'see'
    },
    {
      'lessonId': 'basic_2',
      'order': 12,
      'category': 'basics',
      'content': 'No',
      'translation': 'No',
      'pronunciation': 'noh'
    },
    {
      'lessonId': 'basic_3',
      'order': 13,
      'category': 'basics',
      'content': 'Per favore',
      'translation': 'Please',
      'pronunciation': 'pehr fah-voh-reh'
    },
    {
      'lessonId': 'basic_4',
      'order': 14,
      'category': 'basics',
      'content': 'Grazie',
      'translation': 'Thank you',
      'pronunciation': 'grah-tsee-eh'
    },
    {
      'lessonId': 'basic_5',
      'order': 15,
      'category': 'basics',
      'content': 'Prego',
      'translation': 'You\'re welcome',
      'pronunciation': 'preh-goh'
    },
    {
      'lessonId': 'basic_6',
      'order': 16,
      'category': 'basics',
      'content': 'Scusa (Scusi)',
      'translation': 'Sorry (informal/formal)',
      'pronunciation': 'skoo-zah (skoo-zee)'
    },
    {
      'lessonId': 'basic_7',
      'order': 17,
      'category': 'basics',
      'content': 'Non capisco',
      'translation': 'I don\'t understand',
      'pronunciation': 'non kah-pee-skoh'
    },
    {
      'lessonId': 'basic_8',
      'order': 18,
      'category': 'basics',
      'content': 'Parla inglese?',
      'translation': 'Do you speak English?',
      'pronunciation': 'par-lah een-gleh-zeh'
    },
    {
      'lessonId': 'basic_9',
      'order': 19,
      'category': 'basics',
      'content': 'Non lo so',
      'translation': 'I don\'t know',
      'pronunciation': 'non loh soh'
    },
    {
      'lessonId': 'basic_10',
      'order': 20,
      'category': 'basics',
      'content': 'Mi chiamo...',
      'translation': 'My name is...',
      'pronunciation': 'mee kyah-moh'
    },

    // ========== FOOD (10 lessons) ==========
    {
      'lessonId': 'food_1',
      'order': 21,
      'category': 'food',
      'content': 'Vorrei...',
      'translation': 'I would like...',
      'pronunciation': 'vor-ray'
    },
    {
      'lessonId': 'food_2',
      'order': 22,
      'category': 'food',
      'content': 'Un caffè, per favore',
      'translation': 'A coffee, please',
      'pronunciation': 'oon kahf-feh pehr fah-voh-reh'
    },
    {
      'lessonId': 'food_3',
      'order': 23,
      'category': 'food',
      'content': 'Acqua',
      'translation': 'Water',
      'pronunciation': 'ahk-kwah'
    },
    {
      'lessonId': 'food_4',
      'order': 24,
      'category': 'food',
      'content': 'Pane',
      'translation': 'Bread',
      'pronunciation': 'pah-neh'
    },
    {
      'lessonId': 'food_5',
      'order': 25,
      'category': 'food',
      'content': 'Pasta',
      'translation': 'Pasta',
      'pronunciation': 'pah-stah'
    },
    {
      'lessonId': 'food_6',
      'order': 26,
      'category': 'food',
      'content': 'Pizza',
      'translation': 'Pizza',
      'pronunciation': 'peet-tsah'
    },
    {
      'lessonId': 'food_7',
      'order': 27,
      'category': 'food',
      'content': 'Il conto, per favore',
      'translation': 'The bill, please',
      'pronunciation': 'eel kon-toh pehr fah-voh-reh'
    },
    {
      'lessonId': 'food_8',
      'order': 28,
      'category': 'food',
      'content': 'Sono vegetariano/a',
      'translation': 'I am vegetarian (m/f)',
      'pronunciation': 'soh-noh veh-jeh-tah-ree-ah-noh/ah'
    },
    {
      'lessonId': 'food_9',
      'order': 29,
      'category': 'food',
      'content': 'Delizioso!',
      'translation': 'Delicious!',
      'pronunciation': 'deh-lee-tsee-oh-zoh'
    },
    {
      'lessonId': 'food_10',
      'order': 30,
      'category': 'food',
      'content': 'Salute!',
      'translation': 'Cheers!',
      'pronunciation': 'sah-loo-teh'
    },

    // ========== TRAVEL (10 lessons) ==========
    {
      'lessonId': 'travel_1',
      'order': 31,
      'category': 'travel',
      'content': 'Dov\'è...?',
      'translation': 'Where is...?',
      'pronunciation': 'doh-veh'
    },
    {
      'lessonId': 'travel_2',
      'order': 32,
      'category': 'travel',
      'content': 'Dove sono i bagni?',
      'translation': 'Where are the bathrooms?',
      'pronunciation': 'doh-veh soh-noh ee ban-yee'
    },
    {
      'lessonId': 'travel_3',
      'order': 33,
      'category': 'travel',
      'content': 'Quanto costa un biglietto?',
      'translation': 'How much is a ticket?',
      'pronunciation': 'kwan-toh koh-stah oon beel-yet-toh'
    },
    {
      'lessonId': 'travel_4',
      'order': 34,
      'category': 'travel',
      'content': 'A che ora parte il treno?',
      'translation': 'What time does the train leave?',
      'pronunciation': 'ah keh oh-rah par-teh eel treh-noh'
    },
    {
      'lessonId': 'travel_5',
      'order': 35,
      'category': 'travel',
      'content': 'Un hotel',
      'translation': 'A hotel',
      'pronunciation': 'oon oh-tel'
    },
    {
      'lessonId': 'travel_6',
      'order': 36,
      'category': 'travel',
      'content': 'Una camera',
      'translation': 'A room',
      'pronunciation': 'oo-nah kah-meh-rah'
    },
    {
      'lessonId': 'travel_7',
      'order': 37,
      'category': 'travel',
      'content': 'Aeroporto',
      'translation': 'Airport',
      'pronunciation': 'ah-eh-roh-por-toh'
    },
    {
      'lessonId': 'travel_8',
      'order': 38,
      'category': 'travel',
      'content': 'Stazione',
      'translation': 'Station',
      'pronunciation': 'stah-tsee-oh-neh'
    },
    {
      'lessonId': 'travel_9',
      'order': 39,
      'category': 'travel',
      'content': 'Destra / Sinistra',
      'translation': 'Right / Left',
      'pronunciation': 'deh-strah / see-nee-strah'
    },
    {
      'lessonId': 'travel_10',
      'order': 40,
      'category': 'travel',
      'content': 'Dritto',
      'translation': 'Straight ahead',
      'pronunciation': 'dree-toh'
    },

    // ========== SHOPPING (10 lessons) ==========
    {
      'lessonId': 'shopping_1',
      'order': 41,
      'category': 'shopping',
      'content': 'Quanto costa?',
      'translation': 'How much does it cost?',
      'pronunciation': 'kwan-toh koh-stah'
    },
    {
      'lessonId': 'shopping_2',
      'order': 42,
      'category': 'shopping',
      'content': 'Posso provarlo?',
      'translation': 'Can I try it on?',
      'pronunciation': 'pos-soh proh-var-loh'
    },
    {
      'lessonId': 'shopping_3',
      'order': 43,
      'category': 'shopping',
      'content': 'Taglia piccola/media/grande',
      'translation': 'Size small/medium/large',
      'pronunciation': 'tah-lyah peek-koh-lah/meh-dyah/gran-deh'
    },
    {
      'lessonId': 'shopping_4',
      'order': 44,
      'category': 'shopping',
      'content': 'Accettate carte di credito?',
      'translation': 'Do you accept credit cards?',
      'pronunciation': 'ah-chet-tah-teh kar-teh dee kreh-dee-toh'
    },
    {
      'lessonId': 'shopping_5',
      'order': 45,
      'category': 'shopping',
      'content': 'Sconto',
      'translation': 'Discount',
      'pronunciation': 'skon-toh'
    },
    {
      'lessonId': 'shopping_6',
      'order': 46,
      'category': 'shopping',
      'content': 'Troppo caro',
      'translation': 'Too expensive',
      'pronunciation': 'trohp-poh kah-roh'
    },
    {
      'lessonId': 'shopping_7',
      'order': 47,
      'category': 'shopping',
      'content': 'Mi piace',
      'translation': 'I like it',
      'pronunciation': 'mee pyah-cheh'
    },
    {
      'lessonId': 'shopping_8',
      'order': 48,
      'category': 'shopping',
      'content': 'Non mi piace',
      'translation': 'I don\'t like it',
      'pronunciation': 'non mee pyah-cheh'
    },
    {
      'lessonId': 'shopping_9',
      'order': 49,
      'category': 'shopping',
      'content': 'Lo prendo',
      'translation': 'I\'ll take it',
      'pronunciation': 'loh pren-doh'
    },
    {
      'lessonId': 'shopping_10',
      'order': 50,
      'category': 'shopping',
      'content': 'Un regalo',
      'translation': 'A gift',
      'pronunciation': 'oon reh-gah-loh'
    }
  ]
};

// import 'package:cloud_firestore/cloud_firestore.dart';
//
// final Map<String, dynamic> beginnerItalianCourse = {
//   'courseId': 'italian_beginner',
//   'courseName': 'Beginner Italian',
//   'description': '50 essential Italian phrases for daily conversations',
//   'level': 'beginner',
//   'totalLessons': 50,
//   'totalDuration': 50,
//   'categories': ['greetings', 'basics', 'food', 'travel', 'shopping', 'emergencies'],
//   'createdAt': FieldValue.serverTimestamp(),
//   'updatedAt': FieldValue.serverTimestamp(),
//   'lessons': [
//     // ===== GREETINGS (Lessons 1-10) =====
//     {
//       'lessonId': 'italian_beginner_1',
//       'order': 1,
//       'category': 'greetings',
//       'type': 'dual',
//       'content': 'Ciao',
//       'translation': 'Hello/Goodbye',
//       'pronunciation': 'chow',
//       'notes': 'Informal, used with friends',
//       'isCompleted': false,
//       'lastPracticed': null,
//     },
//     {
//       'lessonId': 'italian_beginner_2',
//       'order': 2,
//       'category': 'greetings',
//       'type': 'dual',
//       'content': 'Buongiorno',
//       'translation': 'Good morning',
//       'pronunciation': 'bwon-jor-no',
//       'notes': 'Use until 1 PM',
//     },
//     {
//       'lessonId': 'italian_beginner_3',
//       'order': 3,
//       'category': 'greetings',
//       'type': 'dual',
//       'content': 'Buonasera',
//       'translation': 'Good evening',
//       'pronunciation': 'bwoh-na-seh-ra',
//       'notes': 'Use after 1 PM',
//     },
//     {
//       'lessonId': 'italian_beginner_4',
//       'order': 4,
//       'category': 'greetings',
//       'type': 'dual',
//       'content': 'Arrivederci',
//       'translation': 'Goodbye',
//       'pronunciation': 'ah-ree-veh-der-chee',
//       'notes': 'Formal farewell',
//     },
//     {
//       'lessonId': 'italian_beginner_5',
//       'order': 5,
//       'category': 'greetings',
//       'type': 'dual',
//       'content': 'Come stai?',
//       'translation': 'How are you?',
//       'pronunciation': 'koh-meh stai',
//       'notes': 'Informal version',
//     },
//     {
//       'lessonId': 'italian_beginner_6',
//       'order': 6,
//       'category': 'greetings',
//       'type': 'dual',
//       'content': 'Sto bene, grazie',
//       'translation': 'I\'m fine, thanks',
//       'pronunciation': 'sto beh-neh graht-see-eh',
//     },
//     {
//       'lessonId': 'italian_beginner_7',
//       'order': 7,
//       'category': 'greetings',
//       'type': 'dual',
//       'content': 'E tu?',
//       'translation': 'And you?',
//       'pronunciation': 'eh too',
//     },
//     {
//       'lessonId': 'italian_beginner_8',
//       'order': 8,
//       'category': 'greetings',
//       'type': 'dual',
//       'content': 'Piacere di conoscerti',
//       'translation': 'Nice to meet you',
//       'pronunciation': 'pee-ah-cheh-reh dee koh-noh-sher-tee',
//     },
//     {
//       'lessonId': 'italian_beginner_9',
//       'order': 9,
//       'category': 'greetings',
//       'type': 'dual',
//       'content': 'A domani',
//       'translation': 'See you tomorrow',
//       'pronunciation': 'ah doh-mah-nee',
//     },
//     {
//       'lessonId': 'italian_beginner_10',
//       'order': 10,
//       'category': 'greetings',
//       'type': 'dual',
//       'content': 'Scusa',
//       'translation': 'Excuse me (informal)',
//       'pronunciation': 'skoo-zah',
//     },
//
//     // ===== BASICS (Lessons 11-20) =====
//     {
//       'lessonId': 'italian_beginner_11',
//       'order': 11,
//       'category': 'basics',
//       'type': 'dual',
//       'content': 'Sì',
//       'translation': 'Yes',
//       'pronunciation': 'see',
//     },
//     {
//       'lessonId': 'italian_beginner_12',
//       'order': 12,
//       'category': 'basics',
//       'type': 'dual',
//       'content': 'No',
//       'translation': 'No',
//       'pronunciation': 'noh',
//     },
//     {
//       'lessonId': 'italian_beginner_13',
//       'order': 13,
//       'category': 'basics',
//       'type': 'dual',
//       'content': 'Per favore',
//       'translation': 'Please',
//       'pronunciation': 'pehr fah-voh-reh',
//     },
//     {
//       'lessonId': 'italian_beginner_14',
//       'order': 14,
//       'category': 'basics',
//       'type': 'dual',
//       'content': 'Grazie',
//       'translation': 'Thank you',
//       'pronunciation': 'graht-see-eh',
//     },
//     {
//       'lessonId': 'italian_beginner_15',
//       'order': 15,
//       'category': 'basics',
//       'type': 'dual',
//       'content': 'Prego',
//       'translation': 'You\'re welcome',
//       'pronunciation': 'preh-go',
//     },
//     {
//       'lessonId': 'italian_beginner_16',
//       'order': 16,
//       'category': 'basics',
//       'type': 'dual',
//       'content': 'Non capisco',
//       'translation': 'I don\'t understand',
//       'pronunciation': 'non kah-pee-skoh',
//     },
//     {
//       'lessonId': 'italian_beginner_17',
//       'order': 17,
//       'category': 'basics',
//       'type': 'dual',
//       'content': 'Parla inglese?',
//       'translation': 'Do you speak English?',
//       'pronunciation': 'par-la een-gleh-zeh',
//     },
//     {
//       'lessonId': 'italian_beginner_18',
//       'order': 18,
//       'category': 'basics',
//       'type': 'dual',
//       'content': 'Non lo so',
//       'translation': 'I don\'t know',
//       'pronunciation': 'non loh soh',
//     },
//     {
//       'lessonId': 'italian_beginner_19',
//       'order': 19,
//       'category': 'basics',
//       'type': 'dual',
//       'content': 'Come ti chiami?',
//       'translation': 'What\'s your name?',
//       'pronunciation': 'koh-meh tee kee-ah-mee',
//     },
//     {
//       'lessonId': 'italian_beginner_20',
//       'order': 20,
//       'category': 'basics',
//       'type': 'dual',
//       'content': 'Mi chiamo...',
//       'translation': 'My name is...',
//       'pronunciation': 'mee kee-ah-moh',
//     },
//
//     // ===== FOOD & DINING (Lessons 21-30) =====
//     {
//       'lessonId': 'italian_beginner_21',
//       'order': 21,
//       'category': 'food',
//       'type': 'dual',
//       'content': 'Vorrei...',
//       'translation': 'I would like...',
//       'pronunciation': 'vor-ray',
//     },
//     {
//       'lessonId': 'italian_beginner_22',
//       'order': 22,
//       'category': 'food',
//       'type': 'dual',
//       'content': 'Il menu, per favore',
//       'translation': 'The menu, please',
//       'pronunciation': 'eel meh-noo pehr fah-voh-reh',
//     },
//     {
//       'lessonId': 'italian_beginner_23',
//       'order': 23,
//       'category': 'food',
//       'type': 'dual',
//       'content': 'Acqua',
//       'translation': 'Water',
//       'pronunciation': 'ah-kwah',
//     },
//     {
//       'lessonId': 'italian_beginner_24',
//       'order': 24,
//       'category': 'food',
//       'type': 'dual',
//       'content': 'Pane',
//       'translation': 'Bread',
//       'pronunciation': 'pah-neh',
//     },
//     {
//       'lessonId': 'italian_beginner_25',
//       'order': 25,
//       'category': 'food',
//       'type': 'dual',
//       'content': 'Pasta',
//       'translation': 'Pasta',
//       'pronunciation': 'pahs-tah',
//     },
//     {
//       'lessonId': 'italian_beginner_26',
//       'order': 26,
//       'category': 'food',
//       'type': 'dual',
//       'content': 'Pizza',
//       'translation': 'Pizza',
//       'pronunciation': 'peet-sah',
//     },
//     {
//       'lessonId': 'italian_beginner_27',
//       'order': 27,
//       'category': 'food',
//       'type': 'dual',
//       'content': 'Gelato',
//       'translation': 'Ice cream',
//       'pronunciation': 'jeh-lah-toh',
//     },
//     {
//       'lessonId': 'italian_beginner_28',
//       'order': 28,
//       'category': 'food',
//       'type': 'dual',
//       'content': 'Quanto costa?',
//       'translation': 'How much does it cost?',
//       'pronunciation': 'kwan-toh koh-stah',
//     },
//     {
//       'lessonId': 'italian_beginner_29',
//       'order': 29,
//       'category': 'food',
//       'type': 'dual',
//       'content': 'Il conto, per favore',
//       'translation': 'The bill, please',
//       'pronunciation': 'eel kon-toh pehr fah-voh-reh',
//     },
//     {
//       'lessonId': 'italian_beginner_30',
//       'order': 30,
//       'category': 'food',
//       'type': 'dual',
//       'content': 'È delizioso!',
//       'translation': 'It\'s delicious!',
//       'pronunciation': 'eh deh-lee-tsee-oh-zoh',
//     },
//
//     // ===== TRAVEL (Lessons 31-40) =====
//     {
//       'lessonId': 'italian_beginner_31',
//       'order': 31,
//       'category': 'travel',
//       'type': 'dual',
//       'content': 'Dov\'è...?',
//       'translation': 'Where is...?',
//       'pronunciation': 'doh-veh',
//     },
//     {
//       'lessonId': 'italian_beginner_32',
//       'order': 32,
//       'category': 'travel',
//       'type': 'dual',
//       'content': 'La stazione',
//       'translation': 'The train station',
//       'pronunciation': 'lah stat-zee-oh-neh',
//     },
//     {
//       'lessonId': 'italian_beginner_33',
//       'order': 33,
//       'category': 'travel',
//       'type': 'dual',
//       'content': 'L\'aeroporto',
//       'translation': 'The airport',
//       'pronunciation': 'lah-eh-roh-por-toh',
//     },
//     {
//       'lessonId': 'italian_beginner_34',
//       'order': 34,
//       'category': 'travel',
//       'type': 'dual',
//       'content': 'Un biglietto per...',
//       'translation': 'A ticket to...',
//       'pronunciation': 'oon beel-yet-toh pehr',
//     },
//     {
//       'lessonId': 'italian_beginner_35',
//       'order': 35,
//       'category': 'travel',
//       'type': 'dual',
//       'content': 'A che ora?',
//       'translation': 'At what time?',
//       'pronunciation': 'ah keh oh-rah',
//     },
//     {
//       'lessonId': 'italian_beginner_36',
//       'order': 36,
//       'category': 'travel',
//       'type': 'dual',
//       'content': 'Destra',
//       'translation': 'Right',
//       'pronunciation': 'deh-strah',
//     },
//     {
//       'lessonId': 'italian_beginner_37',
//       'order': 37,
//       'category': 'travel',
//       'type': 'dual',
//       'content': 'Sinistra',
//       'translation': 'Left',
//       'pronunciation': 'see-nee-strah',
//     },
//     {
//       'lessonId': 'italian_beginner_38',
//       'order': 38,
//       'category': 'travel',
//       'type': 'dual',
//       'content': 'Dritto',
//       'translation': 'Straight',
//       'pronunciation': 'dree-toh',
//     },
//     {
//       'lessonId': 'italian_beginner_39',
//       'order': 39,
//       'category': 'travel',
//       'type': 'dual',
//       'content': 'Lontano',
//       'translation': 'Far',
//       'pronunciation': 'lon-tah-no',
//     },
//     {
//       'lessonId': 'italian_beginner_40',
//       'order': 40,
//       'category': 'travel',
//       'type': 'dual',
//       'content': 'Vicino',
//       'translation': 'Near',
//       'pronunciation': 'vee-chee-no',
//     },
//
//     // ===== SHOPPING (Lessons 41-50) =====
//     {
//       'lessonId': 'italian_beginner_41',
//       'order': 41,
//       'category': 'shopping',
//       'type': 'dual',
//       'content': 'Quanto costa?',
//       'translation': 'How much does it cost?',
//       'pronunciation': 'kwan-toh koh-stah',
//     },
//     {
//       'lessonId': 'italian_beginner_42',
//       'order': 42,
//       'category': 'shopping',
//       'type': 'dual',
//       'content': 'Troppo caro',
//       'translation': 'Too expensive',
//       'pronunciation': 'troh-poh kah-roh',
//     },
//     {
//       'lessonId': 'italian_beginner_43',
//       'order': 43,
//       'category': 'shopping',
//       'type': 'dual',
//       'content': 'Accettate carte di credito?',
//       'translation': 'Do you accept credit cards?',
//       'pronunciation': 'ah-chet-tah-teh kar-teh dee kreh-dee-toh',
//     },
//     {
//       'lessonId': 'italian_beginner_44',
//       'order': 44,
//       'category': 'shopping',
//       'type': 'dual',
//       'content': 'Posso provarlo?',
//       'translation': 'Can I try it on?',
//       'pronunciation': 'pos-so pro-var-lo',
//     },
//     {
//       'lessonId': 'italian_beginner_45',
//       'order': 45,
//       'category': 'shopping',
//       'type': 'dual',
//       'content': 'Mi piace',
//       'translation': 'I like it',
//       'pronunciation': 'mee pee-ah-cheh',
//     },
//     {
//       'lessonId': 'italian_beginner_46',
//       'order': 46,
//       'category': 'shopping',
//       'type': 'dual',
//       'content': 'Non mi piace',
//       'translation': 'I don\'t like it',
//       'pronunciation': 'non mee pee-ah-cheh',
//     },
//     {
//       'lessonId': 'italian_beginner_47',
//       'order': 47,
//       'category': 'shopping',
//       'type': 'dual',
//       'content': 'Ha una taglia più piccola?',
//       'translation': 'Do you have a smaller size?',
//       'pronunciation': 'ah oo-nah tah-lyah pyoo peek-koh-lah',
//     },
//     {
//       'lessonId': 'italian_beginner_48',
//       'order': 48,
//       'category': 'shopping',
//       'type': 'dual',
//       'content': 'Lo prendo',
//       'translation': 'I\'ll take it',
//       'pronunciation': 'lo pren-doh',
//     },
//     {
//       'lessonId': 'italian_beginner_49',
//       'order': 49,
//       'category': 'shopping',
//       'type': 'dual',
//       'content': 'Un regalo',
//       'translation': 'A gift',
//       'pronunciation': 'oon reh-gah-lo',
//     },
//     {
//       'lessonId': 'italian_beginner_50',
//       'order': 50,
//       'category': 'shopping',
//       'type': 'dual',
//       'content': 'La ricevuta',
//       'translation': 'The receipt',
//       'pronunciation': 'lah ree-cheh-voo-tah',
//     },
//   ],
// };