// final List<Map<String, dynamic>> intermediateItalianLessons = [
//   {
//     'type': 'dual',
//     'content': 'Potresti aiutarmi, per favore?',
//     'translation': 'Could you help me, please?',
//     'pronunciation': 'poh-TREHS-tee ah-yoo-TAHR-mee, pehr fah-VOH-reh',
//     'notes': 'Used when politely asking for assistance.',
//     'order': '1',
//   },
//   {
//     'type': 'dual',
//     'content': 'Sto cercando un buon ristorante.',
//     'translation': 'I am looking for a good restaurant.',
//     'pronunciation': 'stoh chehr-KAHN-doh oon bwon ree-stoh-RAHN-teh',
//     'notes': 'Useful when traveling and seeking food options.',
//     'order': '2',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanti anni hai?',
//     'translation': 'How old are you?',
//     'pronunciation': 'KWAHN-tee AHN-nee ah-ee',
//     'notes': 'Common when getting to know someone.',
//     'order': '3',
//   },
//   {
//     'type': 'dual',
//     'content': 'Il tempo oggi è bellissimo.',
//     'translation': 'The weather today is beautiful.',
//     'pronunciation': 'eel TEM-poh OD-jee eh bel-LEE-see-moh',
//     'notes': 'Conversation starter about the weather.',
//     'order': '4',
//   },
//   {
//     'type': 'dual',
//     'content': 'Vorrei prenotare una camera.',
//     'translation': 'I would like to book a room.',
//     'pronunciation': 'vor-RAY preh-noh-TAH-reh OO-nah KAH-meh-rah',
//     'notes': 'Useful in hotel or lodging situations.',
//     'order': '5',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanto costa questo vestito?',
//     'translation': 'How much does this dress cost?',
//     'pronunciation': 'KWAHN-toh KOH-stah KWEHS-toh veh-STEE-toh',
//     'notes': 'Used while shopping.',
//     'order': '6',
//   },
//   {
//     'type': 'dual',
//     'content': 'Potresti aiutarmi, per favore?',
//     'translation': 'Could you help me, please?',
//     'pronunciation': 'poh-TREHS-tee ah-yoo-TAHR-mee, pehr fah-VOH-reh',
//     'notes': 'Used when politely asking for assistance.',
//     'order': '7',
//   },
//   {
//     'type': 'dual',
//     'content': 'Sto cercando un buon ristorante.',
//     'translation': 'I am looking for a good restaurant.',
//     'pronunciation': 'stoh chehr-KAHN-doh oon bwon ree-stoh-RAHN-teh',
//     'notes': 'Useful when traveling and seeking food options.',
//     'order': '8',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanti anni hai?',
//     'translation': 'How old are you?',
//     'pronunciation': 'KWAHN-tee AHN-nee ah-ee',
//     'notes': 'Common when getting to know someone.',
//     'order': '9',
//   },
//   {
//     'type': 'dual',
//     'content': 'Il tempo oggi è bellissimo.',
//     'translation': 'The weather today is beautiful.',
//     'pronunciation': 'eel TEM-poh OD-jee eh bel-LEE-see-moh',
//     'notes': 'Conversation starter about the weather.',
//     'order': '10',
//   },
//   {
//     'type': 'dual',
//     'content': 'Vorrei prenotare una camera.',
//     'translation': 'I would like to book a room.',
//     'pronunciation': 'vor-RAY preh-noh-TAH-reh OO-nah KAH-meh-rah',
//     'notes': 'Useful in hotel or lodging situations.',
//     'order': '11',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanto costa questo vestito?',
//     'translation': 'How much does this dress cost?',
//     'pronunciation': 'KWAHN-toh KOH-stah KWEHS-toh veh-STEE-toh',
//     'notes': 'Used while shopping.',
//     'order': '12',
//   },
//   {
//     'type': 'dual',
//     'content': 'Potresti aiutarmi, per favore?',
//     'translation': 'Could you help me, please?',
//     'pronunciation': 'poh-TREHS-tee ah-yoo-TAHR-mee, pehr fah-VOH-reh',
//     'notes': 'Used when politely asking for assistance.',
//     'order': '13',
//   },
//   {
//     'type': 'dual',
//     'content': 'Sto cercando un buon ristorante.',
//     'translation': 'I am looking for a good restaurant.',
//     'pronunciation': 'stoh chehr-KAHN-doh oon bwon ree-stoh-RAHN-teh',
//     'notes': 'Useful when traveling and seeking food options.',
//     'order': '14',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanti anni hai?',
//     'translation': 'How old are you?',
//     'pronunciation': 'KWAHN-tee AHN-nee ah-ee',
//     'notes': 'Common when getting to know someone.',
//     'order': '15',
//   },
//   {
//     'type': 'dual',
//     'content': 'Il tempo oggi è bellissimo.',
//     'translation': 'The weather today is beautiful.',
//     'pronunciation': 'eel TEM-poh OD-jee eh bel-LEE-see-moh',
//     'notes': 'Conversation starter about the weather.',
//     'order': '16',
//   },
//   {
//     'type': 'dual',
//     'content': 'Vorrei prenotare una camera.',
//     'translation': 'I would like to book a room.',
//     'pronunciation': 'vor-RAY preh-noh-TAH-reh OO-nah KAH-meh-rah',
//     'notes': 'Useful in hotel or lodging situations.',
//     'order': '17',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanto costa questo vestito?',
//     'translation': 'How much does this dress cost?',
//     'pronunciation': 'KWAHN-toh KOH-stah KWEHS-toh veh-STEE-toh',
//     'notes': 'Used while shopping.',
//     'order': '18',
//   },
//   {
//     'type': 'dual',
//     'content': 'Potresti aiutarmi, per favore?',
//     'translation': 'Could you help me, please?',
//     'pronunciation': 'poh-TREHS-tee ah-yoo-TAHR-mee, pehr fah-VOH-reh',
//     'notes': 'Used when politely asking for assistance.',
//     'order': '19',
//   },
//   {
//     'type': 'dual',
//     'content': 'Sto cercando un buon ristorante.',
//     'translation': 'I am looking for a good restaurant.',
//     'pronunciation': 'stoh chehr-KAHN-doh oon bwon ree-stoh-RAHN-teh',
//     'notes': 'Useful when traveling and seeking food options.',
//     'order': '20',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanti anni hai?',
//     'translation': 'How old are you?',
//     'pronunciation': 'KWAHN-tee AHN-nee ah-ee',
//     'notes': 'Common when getting to know someone.',
//     'order': '21',
//   },
//   {
//     'type': 'dual',
//     'content': 'Il tempo oggi è bellissimo.',
//     'translation': 'The weather today is beautiful.',
//     'pronunciation': 'eel TEM-poh OD-jee eh bel-LEE-see-moh',
//     'notes': 'Conversation starter about the weather.',
//     'order': '22',
//   },
//   {
//     'type': 'dual',
//     'content': 'Vorrei prenotare una camera.',
//     'translation': 'I would like to book a room.',
//     'pronunciation': 'vor-RAY preh-noh-TAH-reh OO-nah KAH-meh-rah',
//     'notes': 'Useful in hotel or lodging situations.',
//     'order': '23',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanto costa questo vestito?',
//     'translation': 'How much does this dress cost?',
//     'pronunciation': 'KWAHN-toh KOH-stah KWEHS-toh veh-STEE-toh',
//     'notes': 'Used while shopping.',
//     'order': '24',
//   },
//   {
//     'type': 'dual',
//     'content': 'Potresti aiutarmi, per favore?',
//     'translation': 'Could you help me, please?',
//     'pronunciation': 'poh-TREHS-tee ah-yoo-TAHR-mee, pehr fah-VOH-reh',
//     'notes': 'Used when politely asking for assistance.',
//     'order': '25',
//   },
//   {
//     'type': 'dual',
//     'content': 'Sto cercando un buon ristorante.',
//     'translation': 'I am looking for a good restaurant.',
//     'pronunciation': 'stoh chehr-KAHN-doh oon bwon ree-stoh-RAHN-teh',
//     'notes': 'Useful when traveling and seeking food options.',
//     'order': '26',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanti anni hai?',
//     'translation': 'How old are you?',
//     'pronunciation': 'KWAHN-tee AHN-nee ah-ee',
//     'notes': 'Common when getting to know someone.',
//     'order': '27',
//   },
//   {
//     'type': 'dual',
//     'content': 'Il tempo oggi è bellissimo.',
//     'translation': 'The weather today is beautiful.',
//     'pronunciation': 'eel TEM-poh OD-jee eh bel-LEE-see-moh',
//     'notes': 'Conversation starter about the weather.',
//     'order': '28',
//   },
//   {
//     'type': 'dual',
//     'content': 'Vorrei prenotare una camera.',
//     'translation': 'I would like to book a room.',
//     'pronunciation': 'vor-RAY preh-noh-TAH-reh OO-nah KAH-meh-rah',
//     'notes': 'Useful in hotel or lodging situations.',
//     'order': '29',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanto costa questo vestito?',
//     'translation': 'How much does this dress cost?',
//     'pronunciation': 'KWAHN-toh KOH-stah KWEHS-toh veh-STEE-toh',
//     'notes': 'Used while shopping.',
//     'order': '30',
//   },
//   {
//     'type': 'dual',
//     'content': 'Potresti aiutarmi, per favore?',
//     'translation': 'Could you help me, please?',
//     'pronunciation': 'poh-TREHS-tee ah-yoo-TAHR-mee, pehr fah-VOH-reh',
//     'notes': 'Used when politely asking for assistance.',
//     'order': '31',
//   },
//   {
//     'type': 'dual',
//     'content': 'Sto cercando un buon ristorante.',
//     'translation': 'I am looking for a good restaurant.',
//     'pronunciation': 'stoh chehr-KAHN-doh oon bwon ree-stoh-RAHN-teh',
//     'notes': 'Useful when traveling and seeking food options.',
//     'order': '32',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanti anni hai?',
//     'translation': 'How old are you?',
//     'pronunciation': 'KWAHN-tee AHN-nee ah-ee',
//     'notes': 'Common when getting to know someone.',
//     'order': '33',
//   },
//   {
//     'type': 'dual',
//     'content': 'Il tempo oggi è bellissimo.',
//     'translation': 'The weather today is beautiful.',
//     'pronunciation': 'eel TEM-poh OD-jee eh bel-LEE-see-moh',
//     'notes': 'Conversation starter about the weather.',
//     'order': '34',
//   },
//   {
//     'type': 'dual',
//     'content': 'Vorrei prenotare una camera.',
//     'translation': 'I would like to book a room.',
//     'pronunciation': 'vor-RAY preh-noh-TAH-reh OO-nah KAH-meh-rah',
//     'notes': 'Useful in hotel or lodging situations.',
//     'order': '35',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanto costa questo vestito?',
//     'translation': 'How much does this dress cost?',
//     'pronunciation': 'KWAHN-toh KOH-stah KWEHS-toh veh-STEE-toh',
//     'notes': 'Used while shopping.',
//     'order': '36',
//   },
//   {
//     'type': 'dual',
//     'content': 'Potresti aiutarmi, per favore?',
//     'translation': 'Could you help me, please?',
//     'pronunciation': 'poh-TREHS-tee ah-yoo-TAHR-mee, pehr fah-VOH-reh',
//     'notes': 'Used when politely asking for assistance.',
//     'order': '37',
//   },
//   {
//     'type': 'dual',
//     'content': 'Sto cercando un buon ristorante.',
//     'translation': 'I am looking for a good restaurant.',
//     'pronunciation': 'stoh chehr-KAHN-doh oon bwon ree-stoh-RAHN-teh',
//     'notes': 'Useful when traveling and seeking food options.',
//     'order': '38',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanti anni hai?',
//     'translation': 'How old are you?',
//     'pronunciation': 'KWAHN-tee AHN-nee ah-ee',
//     'notes': 'Common when getting to know someone.',
//     'order': '39',
//   },
//   {
//     'type': 'dual',
//     'content': 'Il tempo oggi è bellissimo.',
//     'translation': 'The weather today is beautiful.',
//     'pronunciation': 'eel TEM-poh OD-jee eh bel-LEE-see-moh',
//     'notes': 'Conversation starter about the weather.',
//     'order': '40',
//   },
//   {
//     'type': 'dual',
//     'content': 'Vorrei prenotare una camera.',
//     'translation': 'I would like to book a room.',
//     'pronunciation': 'vor-RAY preh-noh-TAH-reh OO-nah KAH-meh-rah',
//     'notes': 'Useful in hotel or lodging situations.',
//     'order': '41',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanto costa questo vestito?',
//     'translation': 'How much does this dress cost?',
//     'pronunciation': 'KWAHN-toh KOH-stah KWEHS-toh veh-STEE-toh',
//     'notes': 'Used while shopping.',
//     'order': '42',
//   },
//   {
//     'type': 'dual',
//     'content': 'Potresti aiutarmi, per favore?',
//     'translation': 'Could you help me, please?',
//     'pronunciation': 'poh-TREHS-tee ah-yoo-TAHR-mee, pehr fah-VOH-reh',
//     'notes': 'Used when politely asking for assistance.',
//     'order': '43',
//   },
//   {
//     'type': 'dual',
//     'content': 'Sto cercando un buon ristorante.',
//     'translation': 'I am looking for a good restaurant.',
//     'pronunciation': 'stoh chehr-KAHN-doh oon bwon ree-stoh-RAHN-teh',
//     'notes': 'Useful when traveling and seeking food options.',
//     'order': '44',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanti anni hai?',
//     'translation': 'How old are you?',
//     'pronunciation': 'KWAHN-tee AHN-nee ah-ee',
//     'notes': 'Common when getting to know someone.',
//     'order': '45',
//   },
//   {
//     'type': 'dual',
//     'content': 'Il tempo oggi è bellissimo.',
//     'translation': 'The weather today is beautiful.',
//     'pronunciation': 'eel TEM-poh OD-jee eh bel-LEE-see-moh',
//     'notes': 'Conversation starter about the weather.',
//     'order': '46',
//   },
//   {
//     'type': 'dual',
//     'content': 'Vorrei prenotare una camera.',
//     'translation': 'I would like to book a room.',
//     'pronunciation': 'vor-RAY preh-noh-TAH-reh OO-nah KAH-meh-rah',
//     'notes': 'Useful in hotel or lodging situations.',
//     'order': '47',
//   },
//   {
//     'type': 'dual',
//     'content': 'Quanto costa questo vestito?',
//     'translation': 'How much does this dress cost?',
//     'pronunciation': 'KWAHN-toh KOH-stah KWEHS-toh veh-STEE-toh',
//     'notes': 'Used while shopping.',
//     'order': '48',
//   },
// ];

final Map<String, dynamic> intermediateItalianLessons = {
  'language': 'italian',
  'proficiency': 'intermediate',
  'lessons': [
    // ========== CHAPTER 1: Polite Communication (6 lessons) ==========
    {
      'lessonId': 'polite_1',
      'order': 1,
      'category': 'politeness',
      'content': 'Potrebbe ripetere, per favore?',
      'translation': 'Could you repeat that, please?',
      'pronunciation': 'poh-TREHB-beh ree-peh-TEH-reh pehr fah-VOH-reh',
      'notes': 'Formal request for repetition'
    },
    {
      'lessonId': 'polite_2',
      'order': 2,
      'category': 'politeness',
      'content': 'Mi scusi per il disturbo',
      'translation': 'Excuse me for the disturbance',
      'pronunciation': 'mee SKOO-zee pehr eel dee-STOOR-boh',
      'notes': 'When interrupting someone'
    },
    {
      'lessonId': 'polite_3',
      'order': 3,
      'category': 'politeness',
      'content': 'Non vorrei essere scortese, ma...',
      'translation': 'I don\'t want to be rude, but...',
      'pronunciation': 'non vor-RAY ESS-eh-reh skor-TEH-zeh mah',
      'notes': 'Softening a disagreement'
    },
    {
      'lessonId': 'polite_4',
      'order': 4,
      'category': 'politeness',
      'content': 'Se non le dispiace...',
      'translation': 'If you don\'t mind...',
      'pronunciation': 'seh non leh dee-SPYAH-cheh',
      'notes': 'Polite preface to requests'
    },
    {
      'lessonId': 'polite_5',
      'order': 5,
      'category': 'politeness',
      'content': 'Gradirei qualche informazione',
      'translation': 'I would like some information',
      'pronunciation': 'grah-dee-RAY KWAHL-keh een-for-mah-TSYOH-neh',
      'notes': 'Formal way to ask for info'
    },
    {
      'lessonId': 'polite_6',
      'order': 6,
      'category': 'politeness',
      'content': 'La ringrazio anticipatamente',
      'translation': 'Thank you in advance',
      'pronunciation': 'lah reen-GRAH-tsyoh ahn-tee-chee-pah-TAH-men-teh',
      'notes': 'Used in formal letters/emails'
    },

    // ========== CHAPTER 2: Dining & Food (6 lessons) ==========
    {
      'lessonId': 'dining_1',
      'order': 7,
      'category': 'dining',
      'content': 'Avete menu senza glutine?',
      'translation': 'Do you have gluten-free menus?',
      'pronunciation': 'ah-VEH-teh meh-NOO SEN-zah GLOO-tee-neh',
      'notes': 'Dietary restriction question'
    },
    {
      'lessonId': 'dining_2',
      'order': 8,
      'category': 'dining',
      'content': 'Qualcosa di tipico della zona?',
      'translation': 'Something typical of this area?',
      'pronunciation': 'kwal-KOH-zah dee TEE-pee-koh DEL-lah DZOH-nah',
      'notes': 'Asking for local specialties'
    },
    {
      'lessonId': 'dining_3',
      'order': 9,
      'category': 'dining',
      'content': 'Il mio compagno è allergico alle noci',
      'translation': 'My partner is allergic to nuts',
      'pronunciation': 'eel MEE-oh kom-PAH-nyoh eh al-LER-jee-koh AL-leh NOH-chee',
      'notes': 'Important allergy warning'
    },
    {
      'lessonId': 'dining_4',
      'order': 10,
      'category': 'dining',
      'content': 'Potremmo avere un tavolo più tranquillo?',
      'translation': 'Could we have a quieter table?',
      'pronunciation': 'poh-TREHM-moh ah-VEH-reh oon TAH-voh-loh pyoo tran-KWEEL-loh',
      'notes': 'Requesting table change'
    },
    {
      'lessonId': 'dining_5',
      'order': 11,
      'category': 'dining',
      'content': 'Questo vino è secco o dolce?',
      'translation': 'Is this wine dry or sweet?',
      'pronunciation': 'KWEH-stoh VEE-noh eh SEK-koh oh DOL-cheh',
      'notes': 'Wine selection question'
    },
    {
      'lessonId': 'dining_6',
      'order': 12,
      'category': 'dining',
      'content': 'Ci consiglia un digestivo?',
      'translation': 'Would you recommend an after-dinner drink?',
      'pronunciation': 'chee kon-SEE-lyah oon dee-jeh-STEE-voh',
      'notes': 'Asking for liquor recommendations'
    },

    // ========== CHAPTER 3: Shopping & Transactions (6 lessons) ==========
    {
      'lessonId': 'shop_1',
      'order': 13,
      'category': 'shopping',
      'content': 'Accettate resi?',
      'translation': 'Do you accept returns?',
      'pronunciation': 'ah-chet-TAH-teh REH-zee',
      'notes': 'Important return policy question'
    },
    {
      'lessonId': 'shop_2',
      'order': 14,
      'category': 'shopping',
      'content': 'Ha questo in una taglia più grande?',
      'translation': 'Do you have this in a larger size?',
      'pronunciation': 'ah KWEH-stoh een OO-nah TAH-lyah pyoo GRAHN-deh',
      'notes': 'Clothing size request'
    },
    {
      'lessonId': 'shop_3',
      'order': 15,
      'category': 'shopping',
      'content': 'Posso avere uno sconto per pagamento in contanti?',
      'translation': 'Can I get a discount for cash payment?',
      'pronunciation': 'POS-soh ah-VEH-reh OO-noh SKON-toh pehr pah-gah-MEN-toh een kon-TAHN-tee',
      'notes': 'Negotiating price'
    },
    {
      'lessonId': 'shop_4',
      'order': 16,
      'category': 'shopping',
      'content': 'È possibile ordinarlo se non è disponibile?',
      'translation': 'Is it possible to order it if not available?',
      'pronunciation': 'eh pos-SEE-bee-leh or-dee-NAHR-loh seh non eh dee-spon-EE-bee-leh',
      'notes': 'Asking about special orders'
    },
    {
      'lessonId': 'shop_5',
      'order': 17,
      'category': 'shopping',
      'content': 'Qual è la politica di garanzia?',
      'translation': 'What is the warranty policy?',
      'pronunciation': 'kwal eh lah poh-LEE-tee-kah dee gah-RAHN-tsyah',
      'notes': 'Asking about product guarantees'
    },
    {
      'lessonId': 'shop_6',
      'order': 18,
      'category': 'shopping',
      'content': 'Potrebbe farmi vedere il modello precedente?',
      'translation': 'Could you show me the previous model?',
      'pronunciation': 'poh-TREHB-beh FAR-mee veh-DEH-reh eel moh-DEL-loh preh-cheh-DEN-teh',
      'notes': 'Comparing product versions'
    },

    // ========== CHAPTER 4: Transportation (6 lessons) ==========
    {
      'lessonId': 'trans_1',
      'order': 19,
      'category': 'transport',
      'content': 'Dove si cambia per il centro?',
      'translation': 'Where does one change for downtown?',
      'pronunciation': 'DOH-veh see KAHM-byah pehr eel CHEN-troh',
      'notes': 'Asking about transit connections'
    },
    {
      'lessonId': 'trans_2',
      'order': 20,
      'category': 'transport',
      'content': 'Questo biglietto vale per tutta la giornata?',
      'translation': 'Is this ticket valid all day?',
      'pronunciation': 'KWEH-stoh bee-LYET-toh VAH-leh pehr TOOT-tah lah jor-NAH-tah',
      'notes': 'Clarifying ticket validity'
    },
    {
      'lessonId': 'trans_3',
      'order': 21,
      'category': 'transport',
      'content': 'C\'è un supplemento per i bagagli?',
      'translation': 'Is there a surcharge for luggage?',
      'pronunciation': 'cheh oon soop-pleh-MEN-toh pehr ee bah-GAH-lyee',
      'notes': 'Transporting baggage question'
    },
    {
      'lessonId': 'trans_4',
      'order': 22,
      'category': 'transport',
      'content': 'Dobbiamo prenotare i posti?',
      'translation': 'Do we need to reserve seats?',
      'pronunciation': 'dohb-BYAH-moh preh-noh-TAH-reh ee POS-tee',
      'notes': 'Asking about seat reservations'
    },
    {
      'lessonId': 'trans_5',
      'order': 23,
      'category': 'transport',
      'content': 'Qual è la prossima fermata per il museo?',
      'translation': 'What is the next stop for the museum?',
      'pronunciation': 'kwal eh lah PROS-see-mah fer-MAH-tah pehr eel moo-ZEH-oh',
      'notes': 'Navigating public transport'
    },
    {
      'lessonId': 'trans_6',
      'order': 24,
      'category': 'transport',
      'content': 'È questo il treno per Firenze?',
      'translation': 'Is this the train to Florence?',
      'pronunciation': 'eh KWEH-stoh eel TREH-noh pehr fee-REN-tseh',
      'notes': 'Confirming train destination'
    },

    // ========== CHAPTER 5: Accommodation (6 lessons) ==========
    {
      'lessonId': 'hotel_1',
      'order': 25,
      'category': 'accommodation',
      'content': 'Avete una camera con vista mare?',
      'translation': 'Do you have a room with sea view?',
      'pronunciation': 'ah-VEH-teh OO-nah KAH-meh-rah kon VEE-stah MAH-reh',
      'notes': 'Requesting specific room features'
    },
    {
      'lessonId': 'hotel_2',
      'order': 26,
      'category': 'accommodation',
      'content': 'A che ora serve la colazione?',
      'translation': 'What time is breakfast served?',
      'pronunciation': 'ah kay OH-rah SER-veh lah koh-lah-TSYOH-neh',
      'notes': 'Meal timing question'
    },
    {
      'lessonId': 'hotel_3',
      'order': 27,
      'category': 'accommodation',
      'content': 'Possiamo avere un ritardo nel check-out?',
      'translation': 'Can we have a late check-out?',
      'pronunciation': 'pos-SYAH-moh ah-VEH-reh oon ree-TAHR-doh nel chek-OWT',
      'notes': 'Requesting extended stay'
    },
    {
      'lessonId': 'hotel_4',
      'order': 28,
      'category': 'accommodation',
      'content': 'Dove posso trovare un deposito bagagli?',
      'translation': 'Where can I find luggage storage?',
      'pronunciation': 'DOH-veh POS-soh tro-VAH-reh oon deh-POH-zee-toh bah-GAH-lyee',
      'notes': 'Asking about baggage services'
    },
    {
      'lessonId': 'hotel_5',
      'order': 29,
      'category': 'accommodation',
      'content': 'C\'è il servizio in camera?',
      'translation': 'Is there room service?',
      'pronunciation': 'cheh eel ser-VEE-tsyoh een KAH-meh-rah',
      'notes': 'Asking about hotel amenities'
    },
    {
      'lessonId': 'hotel_6',
      'order': 30,
      'category': 'accommodation',
      'content': 'Potete chiamarci un taxi?',
      'translation': 'Can you call us a taxi?',
      'pronunciation': 'poh-TEH-teh kyah-MAR-chee oon TAHK-see',
      'notes': 'Requesting transportation assistance'
    },

    // ========== CHAPTER 6: Problem Solving (6 lessons) ==========
    {
      'lessonId': 'problem_1',
      'order': 31,
      'category': 'problems',
      'content': 'Mi sono perso, potrebbe aiutarmi?',
      'translation': 'I\'m lost, could you help me?',
      'pronunciation': 'mee SOH-noh PER-soh, poh-TREHB-beh ah-yoo-TAR-mee',
      'notes': 'Asking for directions when lost'
    },
    {
      'lessonId': 'problem_2',
      'order': 32,
      'category': 'problems',
      'content': 'Non funziona il condizionatore',
      'translation': 'The air conditioning isn\'t working',
      'pronunciation': 'non foon-TSYOH-nah eel kon-dee-tsyoh-nah-TOH-reh',
      'notes': 'Reporting maintenance issues'
    },
    {
      'lessonId': 'problem_3',
      'order': 33,
      'category': 'problems',
      'content': 'C\'è stato un errore nel conto',
      'translation': 'There was a mistake in the bill',
      'pronunciation': 'cheh STAH-toh oon eh-ROH-reh nel KON-toh',
      'notes': 'Disputing incorrect charges'
    },
    {
      'lessonId': 'problem_4',
      'order': 34,
      'category': 'problems',
      'content': 'Dove posso trovare un medico?',
      'translation': 'Where can I find a doctor?',
      'pronunciation': 'DOH-veh POS-soh tro-VAH-reh oon MEH-dee-koh',
      'notes': 'Medical emergency question'
    },
    {
      'lessonId': 'problem_5',
      'order': 35,
      'category': 'problems',
      'content': 'Mi hanno rubato il portafoglio',
      'translation': 'My wallet was stolen',
      'pronunciation': 'mee AHN-noh roo-BAH-toh eel por-tah-FOH-lyoh',
      'notes': 'Reporting theft to authorities'
    },
    {
      'lessonId': 'problem_6',
      'order': 36,
      'category': 'problems',
      'content': 'Non riesco a connettermi al WiFi',
      'translation': 'I can\'t connect to the WiFi',
      'pronunciation': 'non ree-EH-sko ah kon-net-TER-mee ahl WEE-fee',
      'notes': 'Troubleshooting tech issues'
    }
  ]
};