// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5yLKp3i81YLEdmqSKQlidP57qyxEkCAA',
    appId: '1:725557012973:web:89e4d26bdd265854bf1fe4',
    messagingSenderId: '725557012973',
    projectId: 'language-learner-app-d2545',
    authDomain: 'language-learner-app-d2545.firebaseapp.com',
    storageBucket: 'language-learner-app-d2545.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMno-pa8JFILd7hzG5ktBKMZTvafe5yWw',
    appId: '1:725557012973:android:48a2aa3f0987b86fbf1fe4',
    messagingSenderId: '725557012973',
    projectId: 'language-learner-app-d2545',
    storageBucket: 'language-learner-app-d2545.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDnLX1U4s5N5_VPPqUKzJ_xhaeqFnGO8o',
    appId: '1:725557012973:ios:1f8ab822a4c8964bbf1fe4',
    messagingSenderId: '725557012973',
    projectId: 'language-learner-app-d2545',
    storageBucket: 'language-learner-app-d2545.firebasestorage.app',
    iosBundleId: 'com.gujjartech.flutterProject',
  );
}
